# Generated by Django 3.1 on 2020-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
