# Generated by Django 3.1 on 2020-08-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200823_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=' cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDescribtion',
            field=models.TextField(verbose_name='product decribtion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDName',
            field=models.CharField(max_length=100, verbose_name='product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='decimal'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIimage', models.ImageField(upload_to='produt/')),
                ('PRDIProdect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
    ]
