# Generated by Django 3.1 on 2020-08-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200823_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATName2',
            field=models.CharField(default='', max_length=50, verbose_name='Name2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Parent Namae'),
        ),
    ]
