# Generated by Django 3.1 on 2020-08-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_catname2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.CreateModel(
            name='Product_Alternntive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNPoduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='products.product')),
            ],
        ),
    ]
