# Generated by Django 3.1 on 2020-08-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_alternntive_palnalternative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_alternntive',
            options={'verbose_name': 'Product_Alternntive', 'verbose_name_plural': 'Products_Alternntive'},
        ),
        migrations.CreateModel(
            name='Product_Aessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternative', models.ManyToManyField(related_name='product_Accessories', to='products.Product')),
                ('PACCPoduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_product', to='products.product')),
            ],
            options={
                'verbose_name': 'Product_Aessory',
                'verbose_name_plural': 'Product_Aessories',
            },
        ),
    ]
