# Generated by Django 3.1 on 2020-08-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200824_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_aessories',
            name='PACCAlternative',
            field=models.ManyToManyField(related_name='product_Accessories', to='products.Product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_aessories',
            name='PACCPoduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_product', to='products.product', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product_alternntive',
            name='PALNAlternative',
            field=models.ManyToManyField(related_name='product_alernative', to='products.Product', verbose_name='Alterntives'),
        ),
        migrations.AlterField(
            model_name='product_alternntive',
            name='PALNPoduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='products.product', verbose_name='Nmae'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIimage',
            field=models.ImageField(upload_to='media/', verbose_name='Im'),
        ),
    ]
