# Generated by Django 3.1 on 2020-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200824_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='PRDIimage',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Iamge'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Iamge'),
        ),
    ]
