# Generated by Django 3.1 on 2020-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Price'),
        ),
    ]
