# Generated by Django 3.1 on 2020-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200828_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDBeastsaller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price'),
        ),
    ]
