# Generated by Django 3.1 on 2020-09-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_auto_20200829_1623'),
        ('products', '0017_order_orderitems_shippingaderess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acounts.profile')),
            ],
        ),
    ]
