# Generated by Django 3.1 on 2020-09-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200905_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costomer',
            old_name='coustomer',
            new_name='user',
        ),
    ]
