# Generated by Django 3.1 on 2020-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRBDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Brand  Description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Variant  Description'),
        ),
    ]
